The following tasks were undertaken to familiarise learner with exception handling in python

Task 0: A function that prints x elements of a list.
Task 1: A function that prints an integer with "{:d}".format().
Task 2: A function that prints the first x elements of a list and only integers.
Task 3: A function that divides 2 integers and prints the result.
Task 4: A function that divides element by element 2 lists.
Task 5: A function that raises a type exception.
Task 6: A function that raises a name exception with a message.
